basePath: /
info:
  contact:
    email: aminmuhammad18@gmail.com
    name: Muhammed Ibrahim
  description: This is a simple todo app backend API.
  title: Todo API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
